import React,{useEffect,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {ArrowLeft,ArrowUpRight,Flag,Plus,Clock,Users,ShieldCheck,Wallet,Send,Trophy} from 'lucide-react';
import {toast} from 'sonner';
import {api,errorMessage,districtNames,colors,shortAddress} from '../lib/api';
import {useWallet} from '../context/WalletContext';
import {ActionButton,Empty,Loading,ExternalLink} from '../components/Shared';
import {Input} from '../components/ui/input';
import {Textarea} from '../components/ui/textarea';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '../components/ui/dialog';
import {sendReward,waitForConfirmation} from '../lib/transactions';
const initial={token_id:'',name:'',reward:'',objective:'',rules:'',eligibility:'Open to everyone',ends_at:'',distribution:'One winner, selected by the creator'};
export default function Bounties({tokens}){
 const [params]=useSearchParams(),{wallet,provider,connect,authenticate}=useWallet();
 const [bounties,setBounties]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[filter,setFilter]=useState('all'),[open,setOpen]=useState(false),[form,setForm]=useState(initial),[busy,setBusy]=useState(false),[selected,setSelected]=useState(null),[entries,setEntries]=useState([]),[content,setContent]=useState('');
 const owned=tokens.filter(t=>t.nexus_launched&&t.creator===wallet&&wallet);
 const load=async()=>{try{const r=await api.get('/bounties');setBounties(r.data);setError('');return r.data;}catch(e){setError(errorMessage(e));return [];}finally{setLoading(false);}};
 useEffect(()=>{load().then(data=>{if(params.get('bounty'))setSelected(data.find(b=>b.id===params.get('bounty')) || null);});if(params.get('create')){setForm({...initial,token_id:params.get('create')});setOpen(true);}},[params]);
 useEffect(()=>{setContent('');setEntries([]);if(selected)api.get(`/bounties/${selected.id}/submissions`).then(r=>setEntries(r.data)).catch(()=>{});},[selected]);
 const create=async(e)=>{e.preventDefault();setBusy(true);try{await authenticate();await api.post('/bounties',{...form,reward:Number(form.reward),ends_at:new Date(form.ends_at).toISOString()});setOpen(false);setForm(initial);await load();toast.success('Your bounty is live');}catch(e){toast.error(errorMessage(e));}finally{setBusy(false);}};
 const submit=async(e)=>{e.preventDefault();setBusy(true);try{await authenticate();await api.post(`/bounties/${selected.id}/submissions`,{content});setContent('');setEntries((await api.get(`/bounties/${selected.id}/submissions`)).data);await load();toast.success('Entry submitted');}catch(e){toast.error(errorMessage(e));}finally{setBusy(false);}};
 const award=async(entry)=>{setBusy(true);try{await authenticate();const key=`nexus-payout-${selected.id}-${entry.id}`;let signature=localStorage.getItem(key);if(signature)await waitForConfirmation(signature);else signature=await sendReward(provider,wallet,entry.wallet,selected.reward,s=>localStorage.setItem(key,s));await api.post(`/bounties/${selected.id}/award`,{submission_id:entry.id,signature});localStorage.removeItem(key);await load();setSelected({...selected,status:'awarded',winner:entry.wallet,payout_signature:signature});toast.success('Reward distributed on Solana');}catch(e){toast.error(errorMessage(e));}finally{setBusy(false);}};
 const field=k=>e=>setForm({...form,[k]:e.target.value});
 const visible=bounties.filter(b=>filter==='all'||(filter==='mine'?b.creator===wallet:b.status===filter));
 return <main className="content-page bounties-page" data-testid="bounties-page"><div className="page-breadcrumb"><Link to="/world" data-testid="bounties-back-world"><ArrowLeft size={15}/>Back to world</Link><span>/</span><span>Bounty board</span></div><div className="page-title-row"><div><div className="eyebrow">CREATORS SET THE CHALLENGE. COMMUNITIES MAKE IT HAPPEN.</div><h1 data-testid="bounties-heading">Make your mark.</h1><p>Real communities. Open possibilities. Rewards worth building for.</p></div><ActionButton data-testid="create-bounty-button" onClick={()=>{setOpen(true);setForm({...initial,token_id:owned[0]?.id || ''});}}><Plus size={16}/>Create a bounty</ActionButton></div><div className="bounty-overview"><div><Flag size={21}/><span><small>OPEN BOUNTIES</small><strong data-testid="open-bounties-count">{bounties.filter(b=>b.status==='open').length.toString().padStart(2,'0')}</strong></span></div><div><Trophy size={21}/><span><small>OFFERED REWARDS</small><strong data-testid="offered-rewards">{bounties.filter(b=>b.status==='open').reduce((s,b)=>s+b.reward,0)} <small>SOL</small></strong></span></div><div><Users size={21}/><span><small>COMMUNITY ENTRIES</small><strong data-testid="bounty-entry-count">{bounties.reduce((s,b)=>s+b.entries,0).toString().padStart(2,'0')}</strong></span></div></div><div className="simple-tabs bounty-tabs">{[['all','All bounties'],['open','Open'],['awarded','Completed'],['mine','My bounties']].map(([id,name])=><button key={id} data-testid={`bounty-filter-${id}`} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{name}</button>)}</div>
 {loading?<Loading text="Opening the bounty board…"/>:error?<Empty icon={Flag} title="Bounties could not load" text={error} testId="bounties-error"><button data-testid="retry-bounties" onClick={load}>Try again</button></Empty>:visible.length?<div className="bounty-grid">{visible.map(b=><button key={b.id} data-testid={`bounty-card-${b.id}`} className="bounty-card" onClick={()=>setSelected(b)} style={{'--district-color':colors[b.district]}}><div className="bounty-card-location"><span className="district-dot" style={{background:colors[b.district]}}/>{districtNames[b.district]}<span>{b.status}</span></div><h2>{b.name}</h2><p>{b.objective}</p><div className="bounty-reward">{b.reward} <small>SOL</small><ArrowUpRight size={20}/></div><div className="bounty-card-footer"><span>{b.token_symbol}</span><span><Users size={13}/>{b.entries} entries</span><span><Clock size={13}/>{new Date(b.ends_at).toLocaleDateString()}</span></div></button>)}</div>:<div className="bounty-empty-world"><div className="bounty-flag-illustration"><div className="bounty-grid-floor"/><Flag size={62} strokeWidth={1}/><span className="orbit-square"/></div><Empty title={filter==='mine'?'Your next community chapter.':'The city is waiting for its first challenge.'} text={filter==='mine'?'Bounties created by your wallet appear here.':'Establish a token territory and give your community something to build together.'} testId="bounties-empty"><Link to="/launch" className="text-cta" data-testid="bounty-launch-token">Establish your territory<ArrowUpRight size={16}/></Link></Empty></div>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="nexus-dialog bounty-create-dialog" data-testid="create-bounty-dialog"><DialogTitle>Create the challenge.</DialogTitle><DialogDescription>Your territory. Your rules.</DialogDescription>{!wallet?<Empty icon={Wallet} title="Connect your creator wallet"><ActionButton data-testid="bounty-connect-wallet" onClick={()=>{setOpen(false);connect();}}>Connect wallet</ActionButton></Empty>:!owned.length?<Empty icon={Flag} title="A territory comes first." text="Only the wallet that launched a token can create its bounties."><Link to="/launch" data-testid="bounty-go-launch" onClick={()=>setOpen(false)} className="text-cta">Launch a token<ArrowUpRight size={15}/></Link></Empty>:<form className="nexus-form" onSubmit={create}><label>Token territory<select data-testid="bounty-token-select" value={form.token_id} onChange={field('token_id')} required><option value="">Select your token</option>{owned.map(t=><option key={t.id} value={t.id}>{t.name} ({t.symbol})</option>)}</select></label><div className="form-two-columns"><label>Bounty name<Input data-testid="bounty-name" value={form.name} onChange={field('name')} minLength={3} maxLength={80} required/></label><label>Reward (SOL)<Input data-testid="bounty-reward" value={form.reward} onChange={field('reward')} type="number" min="0.000001" step="0.000001" max="100000" required/></label></div><label>Objective<Textarea data-testid="bounty-objective" value={form.objective} onChange={field('objective')} minLength={10} maxLength={2000} required/></label><label>Rules & conditions<Textarea data-testid="bounty-rules" value={form.rules} onChange={field('rules')} maxLength={2000}/></label><div className="form-two-columns"><label>Eligibility<Input data-testid="bounty-eligibility" value={form.eligibility} onChange={field('eligibility')} maxLength={500} required/></label><label>Closing date<Input data-testid="bounty-end-date" type="datetime-local" value={form.ends_at} onChange={field('ends_at')} required/></label></div><label>Winner selection / distribution<Input data-testid="bounty-distribution" value={form.distribution} onChange={field('distribution')} maxLength={500} required/></label><p className="inline-info" data-testid="bounty-funding-notice"><ShieldCheck size={15}/>Creator-funded. Rewards are not held in escrow. Payout requires a separate wallet-approved SOL transfer.</p><ActionButton data-testid="publish-bounty" disabled={busy}>{busy?'Publishing…':'Publish bounty'}<ArrowUpRight size={16}/></ActionButton></form>}</DialogContent></Dialog>
 <Dialog open={!!selected} onOpenChange={value=>{if(!value)setSelected(null);}}><DialogContent className="nexus-dialog bounty-detail-dialog" data-testid="bounty-detail-dialog"><DialogTitle>{selected?.name}</DialogTitle><DialogDescription>{selected?.token_symbol} · {districtNames[selected?.district]}</DialogDescription>{selected&&<><div className="bounty-detail-reward" data-testid="bounty-detail-reward">{selected.reward} SOL <span>{selected.status}</span></div><dl className="bounty-details">{[['Objective',selected.objective],['Rules & conditions',selected.rules || 'No additional conditions'],['Eligibility',selected.eligibility],['Winner selection',selected.distribution],['Closes',new Date(selected.ends_at).toLocaleString()]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="inline-info" data-testid="bounty-reward-policy">Creator-managed reward · No escrow</div>{selected.payout_signature&&<ExternalLink testId="bounty-payout-explorer" href={`${process.env.REACT_APP_EXPLORER_URL}/tx/${selected.payout_signature}`}>View confirmed payout</ExternalLink>}<h2>Entries ({entries.length})</h2>{entries.map(entry=><article key={entry.id} className="bounty-entry" data-testid={`bounty-entry-${entry.id}`}><strong>{shortAddress(entry.wallet)}</strong><p>{entry.content}</p>{wallet===selected.creator&&selected.status!=='awarded'&&<ActionButton data-testid={`award-entry-${entry.id}`} disabled={busy} onClick={()=>award(entry)}>{busy?'Processing…':`Award & pay ${selected.reward} SOL`}</ActionButton>}</article>)}{selected.status==='open'&&wallet!==selected.creator&&!entries.some(e=>e.wallet===wallet)&&<form className="nexus-form" onSubmit={submit}><label>Your entry<Textarea data-testid="bounty-submission" placeholder="Share your work, links, and the story behind it." value={content} onChange={e=>setContent(e.target.value)} minLength={10} maxLength={3000} required/></label><ActionButton data-testid="submit-bounty-entry" disabled={busy}><Send size={14}/>{busy?'Submitting…':wallet?'Submit entry':'Connect & submit'}</ActionButton></form>}</>}</DialogContent></Dialog>
 </main>;
}