import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowUpRight,BookOpen,ChevronDown} from 'lucide-react';
import {SiteFooter} from '../components/SiteFooter';

const chapters=[
 {id:'getting-started',title:'Getting started',intro:'NEXUS connects token discovery, communities, and launching in one world.',items:[['Start from Home','Get an overview, then choose World, Launch, or Community. No wallet is needed to browse.'],['Explore the World','Move around the map and select a token building. Its page opens with its identity, market data, and community.'],['Connect when you’re ready','A Solana wallet is required for posting, following, image uploads, and launching. NEXUS supports Phantom and Solflare.']],to:'/world',action:'Enter the World'},
 {id:'world-and-tokens',title:'World & tokens',intro:'Each token has a building, a token page, and a place in the community.',items:[['Buildings and market data','Building height reflects available market capitalization. Market data comes from external providers and can be delayed or unavailable. Missing values are not estimates.'],['NEXUS launches and independent tokens','Tokens launched through NEXUS appear after on-chain confirmation. Five independently launched token identities are also included in the world and labeled as independent tokens. They are not claimed as NEXUS launches.'],['Finding a token','Use the World search to find a name, ticker, or mint address. You can also select its building directly. Token pages link to the exact mint on Pump.fun and Solscan.']],to:'/world',action:'Explore tokens'},
 {id:'communities',title:'Communities',intro:'Find your people in a token community, or follow conversations across NEXUS.',items:[['Directory and shared feed','The Community directory lists live token communities. All posts brings their conversations together. Open a community to publish a new post.'],['Posts and connections','Signed-in members can post text or images, reply, like, repost, edit their profile, and follow other members. An author can delete their own posts.'],['Creator announcements','Announcements and creator controls are reserved for a verified token creator. Listing an independent token does not grant anyone ownership of it.']],to:'/community',action:'Discover communities'},
 {id:'launching',title:'Launching a token',intro:'Create through NEXUS using the existing official Pump.fun integration.',items:[['1. Prepare your token','Connect your wallet, add a name, ticker, image, and description. Choose a neighborhood and building accent.'],['2. Review and approve','A launch is a real, irreversible Solana mainnet transaction. Review the transaction in your wallet; SOL is required for network fees and account rent. Pump.fun creator fees remain unchanged.'],['3. Wait for confirmation','NEXUS registers the token only after its launch transaction is confirmed and verified. The building and community are then created. If a launch is pending, use Check launch status rather than creating a duplicate.']],to:'/launch',action:'Open the launch form'},
 {id:'wallet-and-safety',title:'Wallet & safety',intro:'Keep control of your wallet and understand what you approve.',items:[['Sign-in is not a transaction','The sign-in message proves you own your wallet. It does not authorize transactions. NEXUS never asks for your seed phrase or private key.'],['Check before signing','Launching, trading, or paying a bounty is different from signing in and may spend real funds. Check the mint, destination, amount, and network in your wallet.'],['Understand the risk','Crypto tokens are volatile. Inclusion in the world is not an endorsement or a promise of value. Market data and third-party services may be delayed, incomplete, or unavailable.']],to:'/about',action:'About NEXUS'},
];
export default function Docs(){
 const [active,setActive]=useState('getting-started');const chapter=chapters.find(c=>c.id===active);
 return <main className="docs-page" data-testid="docs-page"><div className="section-wrap editorial-page"><header className="docs-heading"><span className="section-kicker" data-testid="docs-kicker"><BookOpen size={14}/>NEXUS DOCS</span><h1 data-testid="docs-title">A little clarity.<br/><span>A better beginning.</span></h1><p data-testid="docs-description">The essentials, from your first visit to your first launch.</p></header><div className="docs-layout"><nav className="docs-chapters" aria-label="Documentation chapters">{chapters.map(c=><button key={c.id} data-testid={`docs-chapter-${c.id}`} className={active===c.id?'active':''} aria-current={active===c.id?'page':undefined} onClick={()=>setActive(c.id)}>{c.title}<ArrowUpRight size={14}/></button>)}</nav><div className="docs-mobile-select"><select value={active} onChange={e=>setActive(e.target.value)} aria-label="Documentation chapter" data-testid="docs-chapter-select">{chapters.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><ChevronDown size={15}/></div><article className="docs-article" data-testid="docs-article"><span className="section-kicker" data-testid="docs-chapter-number">0{chapters.indexOf(chapter)+1} / THE ESSENTIALS</span><h2 data-testid="docs-chapter-title">{chapter.title}</h2><p className="docs-intro" data-testid="docs-chapter-intro">{chapter.intro}</p>{chapter.items.map(([title,text],i)=><section key={title}><h3 data-testid={`docs-item-title-${i}`}>{title}</h3><p data-testid={`docs-item-text-${i}`}>{text}</p></section>)}<Link className="primary-cta" to={chapter.to} data-testid="docs-chapter-cta">{chapter.action}<ArrowUpRight size={16}/></Link></article></div></div><SiteFooter/></main>;
}