import React,{useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowLeft,ArrowUpRight,Check,ShieldCheck,LoaderCircle,ImagePlus,RefreshCw} from 'lucide-react';
import {Input} from '../components/ui/input';
import {Textarea} from '../components/ui/textarea';
import {ActionButton} from '../components/Shared';
import {colors,districtNames} from '../lib/api';
import {useNexusLaunch} from '../hooks/useNexusLaunch';

export default function Launch({reloadWorld}){
 const {wallet,connect,form,setForm,image,prepared,pending,busy,uploading,error,step,field,chooseImage,submit,recover,retrySubmission,canRetry}=useNexusLaunch(reloadWorld);
 const [accepted,setAccepted]=useState(false),fileInput=useRef(null);
 return <main className="content-page launch-page" data-testid="launch-page"><div className="page-breadcrumb"><Link to="/world" data-testid="launch-back-world"><ArrowLeft size={15}/>Back to world</Link><span>/</span><span>New territory</span></div><div className="page-title-row"><div><div className="eyebrow">THE NEXT CHAPTER IS YOURS</div><h1 data-testid="launch-heading">Build your place.</h1><p>Launch through NEXUS. Powered by Pump.fun.</p></div><span className="outline-badge" data-testid="launch-provider"><span className="status-dot"/>NEXUS · PUMP.FUN</span></div>
 <div className="launch-layout"><form className="nexus-form launch-form" onSubmit={submit}><section><div className="form-section-title"><span>01</span><h2>Token identity</h2></div><div className="form-two-columns"><label>Token name<Input data-testid="launch-name" value={form.name} onChange={field('name')} maxLength={32} required disabled={busy||!!pending} placeholder="Your token's name"/></label><label>Ticker<Input data-testid="launch-symbol" value={form.symbol} onChange={field('symbol')} pattern="[A-Za-z0-9]+" maxLength={13} required disabled={busy||!!pending} placeholder="TOKEN"/></label></div><label>Token image<input ref={fileInput} data-testid="launch-image-file" type="file" accept="image/png,image/jpeg,image/webp" className="sr-only" onChange={chooseImage} disabled={busy||uploading||!!pending}/><button data-testid="launch-upload-image" type="button" className="social-upload-button" onClick={()=>{if(!wallet){connect();return;}fileInput.current?.click();}} disabled={uploading||busy||!!pending}>{image?<img src={image.url} alt="Token" data-testid="launch-image-preview"/>:<ImagePlus size={24}/>}<span>{uploading?'Uploading…':image?'Change token image':'Upload token image'}<small>PNG, JPEG, WebP · up to 5 MB</small></span></button></label><label>Description<Textarea data-testid="launch-description" maxLength={1000} value={form.description} onChange={field('description')} disabled={busy||!!pending}/></label></section>
 <section><div className="form-section-title"><span>02</span><h2>Choose your neighborhood</h2></div><div className="district-options">{Object.entries(districtNames).map(([id,name])=><button type="button" key={id} data-testid={`launch-district-${id}`} className={form.district===id?'selected':''} style={{'--district-color':colors[id]}} disabled={busy||!!pending||!!prepared} onClick={()=>setForm({...form,district:id,color:colors[id]})}><span className="district-dot" style={{background:colors[id]}}/>{name}{form.district===id&&<Check size={14}/>}</button>)}</div><label>Building accent<div className="color-options">{Object.values(colors).map(color=><button type="button" key={color} data-testid={`launch-color-${color.slice(1)}`} disabled={busy||!!pending||!!prepared} aria-label={`Building color ${color}`} className={form.color===color?'selected':''} style={{background:color}} onClick={()=>setForm({...form,color})}>{form.color===color&&<Check size={14}/>}</button>)}</div></label></section>
 <div className="launch-disclosure" data-testid="pump-fee-policy"><ShieldCheck size={18}/><p>Pump.fun creator fees remain unchanged. This real mainnet launch requires SOL for network fees and account rent. NEXUS registers only its own confirmed launch transaction.</p></div>
 {prepared&&<div className="pending-launch" data-testid="launch-prepared"><strong>Transaction prepared</strong><small data-testid="launch-prepared-mint">Mint: {prepared.mint}</small><small data-testid="launch-network-fee">Network fee: {prepared.network_fee_lamports==null?'Wallet estimate':`${prepared.network_fee_lamports/1e9} SOL`} · account rent additional</small></div>}
 <label className="checkbox-label"><input data-testid="launch-acknowledge" type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)} required/><span>I understand this is an irreversible Solana mainnet transaction.</span></label>
 {error&&<p role="alert" className="pump-form-error" data-testid="launch-error">{error}</p>}
 {pending?<div className="pending-launch" data-testid="launch-pending"><strong data-testid="launch-status-text">{step || 'Launch awaiting confirmation'}</strong><ActionButton data-testid="launch-check-status" type="button" disabled={busy} onClick={recover}><RefreshCw size={15}/>Check launch status</ActionButton>{canRetry&&<ActionButton data-testid="launch-retry-submission" type="button" disabled={busy} onClick={retrySubmission}>Retry signed transaction</ActionButton>}</div>:<ActionButton data-testid="launch-submit" type="submit" disabled={busy||uploading} className="full-width">{busy?<LoaderCircle size={17} className="spin"/>:<ShieldCheck size={17}/>}{busy?step:!wallet?'Connect wallet':prepared?'Sign & launch on Pump.fun':'Prepare NEXUS launch'}{!busy&&<ArrowUpRight size={16}/>}</ActionButton>}
 <p className="inline-info" data-testid="nexus-origin-policy">Mint address and launch session are fixed before approval. Tokens created elsewhere cannot be imported.</p>
 </form><aside className="launch-preview"><div className="preview-scene" style={{'--building-color':form.color}}><div className="preview-grid"/><div className="css-building"><div className="building-top"/><div className="building-front">{Array.from({length:24},(_,i)=><span key={i}/>)}</div><div className="building-side"/></div><span className="preview-token" data-testid="launch-preview-symbol">{form.symbol || 'YOUR TOKEN'}</span><div className="preview-plot"/></div><div className="preview-details"><span className="eyebrow">YOUR FUTURE ADDRESS</span><h2 data-testid="launch-preview-name">{form.name || 'An idea. A building. A beginning.'}</h2><div><span>District</span><strong data-testid="launch-preview-district">{districtNames[form.district]}</strong></div><div><span>Launch infrastructure</span><strong>Pump.fun</strong></div><div><span>Community</span><strong>Created after confirmation</strong></div></div><p className="preview-note">A small beginning. An unlimited skyline.</p></aside></div></main>;
}