import React,{useState} from 'react';
import {RealmLink as Link,useRealmNavigate as useNavigate} from '../context/RealmContext';
import {ArrowLeft,ArrowUpRight,ArrowDownUp,Trophy,Search} from 'lucide-react';
import {TokenAvatar,Change,Loading} from '../components/Shared';
import {money,price,districtNames,colors} from '../lib/api';
export default function Leaderboard({world,loading}){
 const navigate=useNavigate(),[sort,setSort]=useState('market_cap'),[district,setDistrict]=useState('all'),[search,setSearch]=useState('');
 const tokens=(world?.tokens || []).filter(t=>(district==='all'||t.district===district)&&`${t.name} ${t.symbol}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>(b[sort] || 0)-(a[sort] || 0));
 return <main className="content-page leaderboard-page" data-testid="leaderboard-page"><div className="page-breadcrumb"><Link to="/world" data-testid="leaderboard-back-world"><ArrowLeft size={15}/>Back to world</Link><span>/</span><span>Leaderboard</span></div><div className="page-title-row"><div><div className="eyebrow">THE SKYLINE NEVER STANDS STILL</div><h1 data-testid="leaderboard-heading">The city's tallest.</h1><p>Communities shaping the world, one block at a time.</p></div><Trophy size={40} strokeWidth={1} className="page-emblem"/></div><div className="leaderboard-summary">{[['WORLD MARKET CAP',money(world?.stats?.market_cap)],['24H VOLUME',money(world?.stats?.volume_24h)],['TOKEN BUILDINGS',world?.tokens?.length || 0],['DISTRICTS','04']].map(([name,value],i)=><div key={name}><span>{name}</span><strong data-testid={`leaderboard-stat-${i}`}>{value}</strong></div>)}</div><div className="table-filters"><div className="simple-tabs">{[['all','All districts'],...Object.entries(districtNames)].map(([id,name])=><button data-testid={`leaderboard-filter-${id}`} key={id} className={district===id?'active':''} onClick={()=>setDistrict(id)}>{name}</button>)}</div><div className="table-search"><Search size={15}/><input data-testid="leaderboard-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a token"/></div></div>
 {loading&&!world?<Loading/>:<div className="table-scroll"><table className="leaderboard-table" data-testid="leaderboard-table"><thead><tr><th>#</th><th>Token / Territory</th><th>Price</th><th><button data-testid="sort-change" onClick={()=>setSort('change_24h')}>24h change <ArrowDownUp size={12}/></button></th><th><button data-testid="sort-market-cap" onClick={()=>setSort('market_cap')}>Market cap <ArrowDownUp size={12}/></button></th><th><button data-testid="sort-volume" onClick={()=>setSort('volume_24h')}>24h volume <ArrowDownUp size={12}/></button></th><th>District</th><th/></tr></thead><tbody>{tokens.map((t,i)=><tr key={t.id} data-testid={`leaderboard-row-${t.id}`} onClick={()=>navigate(`/token/${t.id}`)}><td className="rank">{String(i+1).padStart(2,'0')}</td><td><Link data-testid={`leaderboard-token-${t.id}`} to={`/token/${t.id}`} className="table-token"><TokenAvatar token={t} size={37}/><span><strong>{t.name}</strong><small>{t.symbol}</small></span></Link></td><td data-testid={`leaderboard-price-${t.id}`}>{price(t.price)}</td><td><Change value={t.change_24h} testId={`leaderboard-change-${t.id}`}/></td><td data-testid={`leaderboard-cap-${t.id}`}>{money(t.market_cap)}</td><td data-testid={`leaderboard-volume-${t.id}`}>{money(t.volume_24h)}</td><td><span className="table-district"><i style={{background:colors[t.district]}}/>{districtNames[t.district]}</span></td><td><ArrowUpRight size={15}/></td></tr>)}</tbody></table>{!tokens.length&&<div className="empty-state" data-testid="leaderboard-empty">No tokens match your search.</div>}</div>}<div className="table-caption" data-testid="leaderboard-source">Market data by DEX Screener <span>{world?.updated_at?`Updated ${new Date(world.updated_at).toLocaleTimeString()}`:'Awaiting data'}</span></div></main>;
}