import React,{useCallback,useEffect,useState} from 'react';
import {useParams} from 'react-router-dom';
import {Copy,Check,ArrowUpRight,ArrowLeft,Globe,SlidersHorizontal,Flag,History} from 'lucide-react';
import {toast} from 'sonner';
import {useRealm,RealmLink as Link} from '../context/RealmContext';
import {useWallet} from '../context/WalletContext';
import {errorMessage,money,price,shortAddress,districtNames} from '../lib/api';
import {TokenAvatar,Change,Loading,Empty,ActionButton,ExternalLink} from '../components/Shared';
import {PriceChart} from '../components/PriceChart';
import {TokenCommunity} from '../components/community/TokenCommunity';
import {PumpTradingPanel} from '../components/PumpTradingPanel';
import {SwapPanel} from '../components/SwapPanel';
import {TradingActivity} from '../components/TradingActivity';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '../components/ui/dialog';
import {Input} from '../components/ui/input';
import {Textarea} from '../components/ui/textarea';

export default function TokenDashboard({reloadWorld}){
 const {id}=useParams(),{api}=useRealm(),{wallet,authenticate}=useWallet();
 const [token,setToken]=useState(null),[error,setError]=useState(''),[tab,setTab]=useState('market'),[copied,setCopied]=useState(false),[activity,setActivity]=useState([]),[bounties,setBounties]=useState([]);
 const [edit,setEdit]=useState(false),[presence,setPresence]=useState({description:'',color:'#b6f36e',image:''}),[saving,setSaving]=useState(false);
 useEffect(()=>{let alive=true;setToken(null);setError('');setTab('market');const load=async()=>{try{const {data}=await api.get(`/tokens/${id}`);if(alive){setToken(data);setPresence({description:data.description||'',image:data.image||'',color:data.color});}}catch(e){if(alive)setError(errorMessage(e));}};load();const timer=setInterval(load,60000);return()=>{alive=false;clearInterval(timer);};},[id,api]);
 const loadActivity=useCallback(()=>{api.get('/activity',{params:{token_id:id}}).then(r=>setActivity(r.data)).catch(()=>{});api.get('/bounties',{params:{token_id:id}}).then(r=>setBounties(r.data)).catch(()=>{});},[api,id]);
 useEffect(()=>{loadActivity();},[loadActivity,tab]);
 const copy=async()=>{try{await navigator.clipboard.writeText(token.mint);setCopied(true);setTimeout(()=>setCopied(false),1800);}catch{toast.error('Clipboard unavailable');}};
 const save=async e=>{e.preventDefault();setSaving(true);try{await authenticate();await api.patch(`/tokens/${id}/presence`,{...presence,image:presence.image||null});setToken(t=>({...t,...presence}));setEdit(false);reloadWorld();toast.success('Territory updated');}catch(e){toast.error(errorMessage(e));}finally{setSaving(false);}};
 if(error)return <main className="content-page"><Empty icon={Globe} title={error} testId="token-error"/></main>;
 if(!token)return <main className="content-page"><Loading text="Entering the territory…"/></main>;
 return <main className="content-page immersive-hub" data-testid="token-dashboard">
  <div className="hub-location" data-testid="token-district"><Link to="/world" data-testid="token-back-world"><ArrowLeft size={14}/>Back to world</Link><i style={{background:token.color}}/>{districtNames[token.district]}<em data-testid="token-origin-label">{token.nexus_launched?'NEXUS launch':'Independent token'}</em></div>
  <div className="hub-identity"><TokenAvatar token={token} size={64}/><div><h1 data-testid="token-name">{token.name}</h1><button data-testid="copy-token-address" title="Copy token address" onClick={copy}><span data-testid="token-ticker">${token.symbol}</span><span>{shortAddress(token.mint)}</span>{copied?<Check size={12}/>:<Copy size={12}/>}</button></div><div className="hub-value"><strong data-testid="token-price">{price(token.price)}</strong><Change value={token.change_24h} testId="token-price-change"/></div><Link to={`/community/${id}`} className="hub-join" data-testid="join-community">Join community<ArrowUpRight size={16}/></Link></div>
  <div className="hub-sections" data-testid="token-hub-sections">{[['market','Overview'],['community','Community'],['territory','About'],['history','Activity'],['trades','Trades']].map(([key,title])=><button key={key} data-testid={`token-tab-${key}`} aria-pressed={tab===key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{title}</button>)}</div>
  {tab==='market'&&<section className="hub-market" data-testid="hub-market"><div className="hub-metrics">{[['Market cap',money(token.market_cap)],['24h volume',money(token.volume_24h)],['Liquidity',money(token.liquidity)],['Holders',token.holders?.toLocaleString()||'Unavailable']].map(([label,value],i)=><div key={label}><small>{label}</small><strong data-testid={`token-stat-${i}`}>{value}</strong></div>)}</div><PriceChart token={token}/><div className="hub-market-bottom"><div className="hub-market-origin" data-testid="pump-token-provenance"><span className="status-dot"/><span>Pump.fun · {token.pump_complete?'Graduated':'Bonding curve'}<small data-testid="pump-market-data-source">{token.market_source||'Awaiting market data'}{token.market_updated_at?` · ${new Date(token.market_updated_at).toLocaleTimeString()}`:''}</small></span></div><ExternalLink testId="token-pump-link" href={`${process.env.REACT_APP_PUMP_FUN_URL}/coin/${token.mint}`}>Trade on Pump.fun</ExternalLink><Link to={`/community/${id}`} data-testid="hub-enter-community">Enter community<ArrowUpRight size={16}/></Link></div></section>}
  {tab==='community'&&<TokenCommunity token={token} compact/>}
  {tab==='territory'&&<section className="hub-territory" data-testid="token-about"><div className="hub-description"><h2 data-testid="token-info-title">About {token.name}</h2><p data-testid="token-description">{token.description}</p><dl><div><dt>Network</dt><dd data-testid="token-network">Solana mainnet</dd></div><div><dt>Mint</dt><dd data-testid="token-full-mint">{token.mint}</dd></div><div><dt>Origin</dt><dd data-testid="token-launch-provider">{token.nexus_launched?'Launched through NEXUS · Pump.fun':'Independently launched · Included in Live World'}</dd></div><div><dt>Creator fees</dt><dd data-testid="token-creator-fees">Managed by Pump.fun. Unchanged.</dd></div></dl><ExternalLink testId="token-solscan" href={`${process.env.REACT_APP_EXPLORER_URL}/token/${token.mint}`}>View on Solscan</ExternalLink>{wallet&&wallet===token.creator&&<ActionButton data-testid="edit-territory" onClick={()=>setEdit(true)}><SlidersHorizontal size={14}/>Customize territory</ActionButton>}</div><div className="hub-bounties"><h2 data-testid="token-bounty-title">Bounty board</h2>{bounties.length?bounties.map(b=><Link key={b.id} to={`/bounties?bounty=${b.id}`} data-testid={`token-bounty-${b.id}`}><Flag size={15}/>{b.name}<strong>{b.reward} SOL</strong></Link>):<p data-testid="token-bounties-empty">No active bounties.</p>}{wallet&&wallet===token.creator&&<Link data-testid="create-token-bounty" to={`/bounties?create=${id}`}>Create a bounty<ArrowUpRight size={14}/></Link>}<Link to="/bounties" data-testid="all-bounties">All bounties<ArrowUpRight size={14}/></Link></div></section>}
  {tab==='history'&&(activity.length?<div className="history-list">{activity.map(a=><div key={a.id} data-testid={`token-history-${a.id}`}><span className="status-dot"/><span>{a.text}<small>{new Date(a.created_at).toLocaleString()}</small></span>{a.signature&&<ExternalLink testId={`history-tx-${a.id}`} href={`${process.env.REACT_APP_EXPLORER_URL}/tx/${a.signature}`}>Transaction</ExternalLink>}</div>)}</div>:<Empty icon={History} title="A new chapter." text="Community contributions will appear here." testId="history-empty"/>)}
  {tab==='trades'&&<div className="hub-trading-view"><TradingActivity token={token}/>{token.pump_verified?<PumpTradingPanel token={token}/>:<SwapPanel token={token}/>}</div>}
  <Dialog open={edit} onOpenChange={setEdit}><DialogContent className="nexus-dialog" data-testid="presence-dialog"><DialogTitle>Make it yours.</DialogTitle><DialogDescription>Customize your territory.</DialogDescription><form className="nexus-form" onSubmit={save}><label>Accent<input data-testid="presence-color" type="color" value={presence.color} onChange={e=>setPresence({...presence,color:e.target.value})}/></label><label>Image URL<Input data-testid="presence-image" type="url" value={presence.image} onChange={e=>setPresence({...presence,image:e.target.value})}/></label><label>Description<Textarea data-testid="presence-description" maxLength={1000} value={presence.description} onChange={e=>setPresence({...presence,description:e.target.value})}/></label><ActionButton data-testid="save-presence" disabled={saving}>Save territory</ActionButton></form></DialogContent></Dialog>
 </main>;
}