import React from 'react';
import {Link} from 'react-router-dom';
import {ArrowUpRight} from 'lucide-react';

const features=[
 {id:'world',number:'01',title:'A different way to discover.',text:'Explore an open world where tokens become buildings. Find one that catches your eye and step inside.',image:'/previews/world-preview.jpg',alt:'The NEXUS map with five real token buildings',link:'/world',action:'Explore the World'},
 {id:'community',number:'02',title:'More than a ticker.',text:'Meet the people behind the conversation. Every token has a place for posts, ideas, and shared momentum.',image:'/previews/token-preview.jpg',alt:'NEXUS token overview with live market information and community access',link:'/community',action:'Find your community'},
 {id:'launch',number:'03',title:'Your idea. Its own address.',text:'Launch through NEXUS, powered by Pump.fun. Your confirmed token gets a building and a community of its own.',image:'/previews/launch-preview.jpg',alt:'NEXUS token launch form and building preview',link:'/launch',action:'Launch a token'},
];
export const ProductPreviews=()=> <section className="home-products section-wrap" aria-labelledby="product-heading"><div className="section-heading"><div><span className="section-kicker" data-testid="product-section-label">A PLACE FOR EVERY PART OF THE JOURNEY</span><h2 id="product-heading" data-testid="product-heading">Explore. Connect. Create.</h2></div><Link to="/about" className="quiet-link" data-testid="home-about-link">The NEXUS idea<ArrowUpRight size={15}/></Link></div><div className="product-previews">{features.map(f=><article key={f.id} className="product-preview" data-testid={`product-preview-${f.id}`}><Link to={f.link} className="preview-image-link" data-testid={`product-image-link-${f.id}`}><div className="preview-browser"><span/><span/><span/><small>NEXUS / {f.id.toUpperCase()}</small><ArrowUpRight size={12}/></div><img data-testid={`product-image-${f.id}`} src={f.image} alt={f.alt} loading="lazy"/></Link><div className="preview-copy"><span className="preview-number" data-testid={`product-number-${f.id}`}>{f.number}</span><h3 data-testid={`product-title-${f.id}`}>{f.title}</h3><p data-testid={`product-description-${f.id}`}>{f.text}</p><Link to={f.link} data-testid={`product-cta-${f.id}`}>{f.action}<ArrowUpRight size={15}/></Link></div></article>)}</div><span className="preview-footnote" data-testid="product-preview-disclosure">Product previews · Market values change in real time</span></section>;